### ISSUE TITLE
Cave Crawler incorrect location description

### ISSUE THREAD

**Issue by Waldxn** [BrastaSauce/turael-skpping#1]
The current overlay states "Relleka Slayer Cave" when it should read "Fremennik Slayer Cave" to better align with the fairy ring description 

![image](https://user-images.githubusercontent.com/29243129/202918209-e8dfb175-0eb0-452a-badf-ee6a6a2d2392.png)

The world map displays "Fremennik Slayer Dungeon" so that may be a good option as well. 
Opened this issue mainly due to it throwing me off on the slayer ring description, thanks for the plugin though! Very helpful.

**Comment by BrastaSauce** [comment]
I changed the location to "Fremennik Slayer Dungeon" to match the world map but kept the Slayer Ring teleport the same as it's called "Relleka Slayer Caves" in that. I added the fairy ring information as well.

Changes will be reflected once the update gets merged. Thanks.
